# /etc/tlp.d/00-custom.conf

TLP_ENABLE=1

#TLP_DISABLE_DEFAULTS=1
#TLP_WARN_LEVEL=3

TLP_AUTO_SWITCH=2

#CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_BOOST_ON_BAT=0
CPU_HWP_DYN_BOOST_ON_BAT=0
NMI_WATCHDOG=0

DISK_DEVICES="nvme0n1"
DISK_IOSCHED="keep"

INTEL_GPU_POWER_PROFILE_ON_BAT=power_saving

WIFI_PWR_ON_BAT=off
#might be tuned in the future
SOUND_POWER_SAVE_ON_BAT=10
SOUND_POWER_SAVE_CONTROLLER=Y

#when using jack (to fix audio pop sound)
#SOUND_POWER_SAVE_ON_BAT=0
#SOUND_POWER_SAVE_CONTROLLER=N

#(this might cause problems?)
#PCIE_ASPM_ON_BAT=powersupersave

RUNTIME_PM_ON_BAT=auto

# potential for usb tuning in the future

#DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
#DEVICES_TO_ENABLE_ON_STARTUP="wifi"
